import type { ImageAsset } from "@/content/types";

/**
 * Curated, verified, freely-licensed (Pexels) stock photos, one per visual
 * theme. Sourced to genuinely match modest fashion / garment manufacturing
 * subject matter — swap any entry for real SamNoor photography later by
 * replacing the URL here; every call site already carries brand-specific alt
 * text independent of this file.
 */
const THEME_PHOTOS: Record<string, string> = {
  "hijab-fashion-model": "https://images.pexels.com/photos/4728705/pexels-photo-4728705.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "hijab-flatlay-chiffon": "https://images.pexels.com/photos/6070106/pexels-photo-6070106.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "hijab-fabric-texture": "https://images.pexels.com/photos/6571744/pexels-photo-6571744.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "hijab-color-range": "https://images.pexels.com/photos/2171218/pexels-photo-2171218.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "abaya-mannequin": "https://images.pexels.com/photos/13838842/pexels-photo-13838842.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "abaya-model": "https://images.pexels.com/photos/10898230/pexels-photo-10898230.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "abaya-fabric-drape": "https://images.pexels.com/photos/4814074/pexels-photo-4814074.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "abaya-seam-detail": "https://images.pexels.com/photos/6801439/pexels-photo-6801439.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "abaya-embellished": "https://images.pexels.com/photos/32208656/pexels-photo-32208656.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "embroidery-closeup": "https://images.pexels.com/photos/18776725/pexels-photo-18776725.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "niqab-fabric": "https://images.pexels.com/photos/6044224/pexels-photo-6044224.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "prayer-dress-flatlay": "https://images.pexels.com/photos/7235669/pexels-photo-7235669.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "prayer-dress-model": "https://images.pexels.com/photos/36211965/pexels-photo-36211965.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "khimar-mannequin": "https://images.pexels.com/photos/4857762/pexels-photo-4857762.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "khimar-model": "https://images.pexels.com/photos/8526279/pexels-photo-8526279.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "jilbab-flatlay": "https://images.pexels.com/photos/6461392/pexels-photo-6461392.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "jilbab-model": "https://images.pexels.com/photos/20841544/pexels-photo-20841544.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "kaftan-model": "https://images.pexels.com/photos/30457749/pexels-photo-30457749.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "innercap-rows": "https://images.pexels.com/photos/30267890/pexels-photo-30267890.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "innercap-model": "https://images.pexels.com/photos/4728651/pexels-photo-4728651.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "scarves-stack": "https://images.pexels.com/photos/2325270/pexels-photo-2325270.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "scarf-model": "https://images.pexels.com/photos/26189511/pexels-photo-26189511.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "instant-hijab-model": "https://images.pexels.com/photos/32349583/pexels-photo-32349583.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "sports-hijab-fabric": "https://images.pexels.com/photos/4863009/pexels-photo-4863009.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "sports-hijab-model": "https://images.pexels.com/photos/7690849/pexels-photo-7690849.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "luxury-hijab-silk": "https://images.pexels.com/photos/34850184/pexels-photo-34850184.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "luxury-hijab-detail": "https://images.pexels.com/photos/36726420/pexels-photo-36726420.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "fabric-roll-generic": "/fabrics/fabric-library-hero.jpg",
  "fabric-nida-matte": "/fabrics/nida.jpg",
  "fabric-korean-nida-sheen": "/fabrics/korean-nida.jpg",
  "fabric-zoom-weave": "/fabrics/zoom.jpg",
  "fabric-chiffon-sheer": "/fabrics/chiffon.jpg",
  "fabric-georgette-crinkle": "/fabrics/georgette.jpg",
  "fabric-rayon-drape": "/fabrics/rayon.jpg",
  "fabric-viscose-weave": "/fabrics/viscose.jpg",
  "fabric-crepe-texture": "/fabrics/crepe.jpg",
  "fabric-cotton-texture": "/fabrics/cotton.jpg",
  "fabric-jersey-stretch": "/fabrics/jersey.jpg",
  "fabric-silk-sheen": "/fabrics/silk.jpg",
  "fabric-linen-texture": "/fabrics/linen.jpg",
  "fabric-premium-blends-stack": "/fabrics/premium-blends.jpg",
  "fabric-swatch-cards": "/fabrics/fabric-swatch-cards.jpg",
  "factory-exterior": "https://images.pexels.com/photos/36006588/pexels-photo-36006588.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "factory-floor-wide": "https://images.pexels.com/photos/31031031/pexels-photo-31031031.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "qc-inspection": "https://images.pexels.com/photos/31090818/pexels-photo-31090818.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "cutting-table": "https://images.pexels.com/photos/7147578/pexels-photo-7147578.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "sewing-floor": "https://images.pexels.com/photos/4492077/pexels-photo-4492077.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "warehouse-cartons": "https://images.pexels.com/photos/10834810/pexels-photo-10834810.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "shipping-containers": "https://images.pexels.com/photos/9716365/pexels-photo-9716365.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "design-desk": "https://images.pexels.com/photos/15764763/pexels-photo-15764763.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "business-headshot-1": "https://images.pexels.com/photos/33261955/pexels-photo-33261955.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "business-headshot-2": "https://images.pexels.com/photos/10347162/pexels-photo-10347162.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "business-headshot-3": "https://images.pexels.com/photos/37148339/pexels-photo-37148339.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "business-headshot-4": "https://images.pexels.com/photos/34381970/pexels-photo-34381970.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "trade-exhibition-booth": "https://images.pexels.com/photos/35138560/pexels-photo-35138560.jpeg?auto=compress&cs=tinysrgb&w=1600",
  "certification-documents": "https://images.pexels.com/photos/10347152/pexels-photo-10347152.jpeg?auto=compress&cs=tinysrgb&w=1600",
};

/** Maps every content seed used across the site to one of the themes above. */
const SEED_THEME_MAP: Record<string, keyof typeof THEME_PHOTOS> = {
  // Products — Aria chiffon hijab
  "prod-aria-1": "hijab-fashion-model",
  "prod-aria-2": "hijab-fabric-texture",
  "prod-aria-3": "hijab-color-range",
  // Nadia jersey hijab
  "prod-nadia-1": "instant-hijab-model",
  "prod-nadia-2": "fabric-jersey-stretch",
  // Layla Nida abaya
  "prod-layla-1": "abaya-mannequin",
  "prod-layla-2": "abaya-fabric-drape",
  "prod-layla-3": "abaya-seam-detail",
  // Zahra embellished abaya
  "prod-zahra-1": "abaya-embellished",
  "prod-zahra-2": "embroidery-closeup",
  // Sana prayer dress
  "prod-sana-1": "prayer-dress-flatlay",
  "prod-sana-2": "prayer-dress-model",
  // Mira khimar
  "prod-mira-1": "khimar-mannequin",
  "prod-mira-2": "abaya-seam-detail",
  // Amira instant hijab
  "prod-amira-1": "instant-hijab-model",
  "prod-amira-2": "hijab-fabric-texture",
  // Zayn sports hijab
  "prod-zayn-1": "sports-hijab-model",
  "prod-zayn-2": "sports-hijab-fabric",
  // Noor silk luxury hijab
  "prod-noor-1": "luxury-hijab-silk",
  "prod-noor-2": "luxury-hijab-detail",
  "prod-noor-3": "luxury-hijab-silk",
  // Hana jilbab
  "prod-hana-1": "jilbab-flatlay",
  "prod-hana-2": "abaya-seam-detail",
  // Rania cotton inner cap
  "prod-rania-1": "innercap-rows",
  "prod-rania-2": "innercap-model",
  // Yara double-layer niqab
  "prod-yara-1": "niqab-fabric",
  "prod-yara-2": "hijab-flatlay-chiffon",
  // Yasmin silk-blend scarf
  "prod-yasmin-1": "scarves-stack",
  "prod-yasmin-2": "scarf-model",

  // Additional catalog expansion products (66 new SKUs across all 11 categories)
  "prod-alia-1": "hijab-fashion-model",
  "prod-alia-2": "hijab-fabric-texture",
  "prod-farah-1": "hijab-fabric-texture",
  "prod-farah-2": "hijab-color-range",
  "prod-dania-1": "hijab-color-range",
  "prod-dania-2": "hijab-flatlay-chiffon",
  "prod-reema-1": "hijab-flatlay-chiffon",
  "prod-reema-2": "hijab-fashion-model",
  "prod-sumaya-1": "hijab-fashion-model",
  "prod-sumaya-2": "hijab-fabric-texture",
  "prod-iman-1": "hijab-fabric-texture",
  "prod-iman-2": "hijab-color-range",
  "prod-salma-1": "abaya-mannequin",
  "prod-salma-2": "abaya-model",
  "prod-widad-1": "abaya-model",
  "prod-widad-2": "abaya-fabric-drape",
  "prod-nailah-1": "abaya-fabric-drape",
  "prod-nailah-2": "abaya-seam-detail",
  "prod-farida-1": "abaya-seam-detail",
  "prod-farida-2": "abaya-embellished",
  "prod-halima-1": "abaya-embellished",
  "prod-halima-2": "embroidery-closeup",
  "prod-safiya-1": "embroidery-closeup",
  "prod-safiya-2": "abaya-mannequin",
  "prod-maryam-1": "prayer-dress-flatlay",
  "prod-maryam-2": "prayer-dress-model",
  "prod-khadija-1": "prayer-dress-model",
  "prod-khadija-2": "prayer-dress-flatlay",
  "prod-ruqayyah-1": "prayer-dress-flatlay",
  "prod-ruqayyah-2": "prayer-dress-model",
  "prod-zaynab-1": "prayer-dress-model",
  "prod-zaynab-2": "prayer-dress-flatlay",
  "prod-asiya-1": "prayer-dress-flatlay",
  "prod-asiya-2": "prayer-dress-model",
  "prod-bilqis-1": "prayer-dress-model",
  "prod-bilqis-2": "prayer-dress-flatlay",
  "prod-sundus-1": "khimar-mannequin",
  "prod-sundus-2": "khimar-model",
  "prod-farhana-1": "khimar-model",
  "prod-farhana-2": "abaya-seam-detail",
  "prod-latifa-1": "abaya-seam-detail",
  "prod-latifa-2": "khimar-mannequin",
  "prod-amani-1": "khimar-mannequin",
  "prod-amani-2": "khimar-model",
  "prod-basma-1": "khimar-model",
  "prod-basma-2": "abaya-seam-detail",
  "prod-naila-1": "abaya-seam-detail",
  "prod-naila-2": "khimar-mannequin",
  "prod-shifa-1": "instant-hijab-model",
  "prod-shifa-2": "hijab-fabric-texture",
  "prod-rukan-1": "hijab-fabric-texture",
  "prod-rukan-2": "instant-hijab-model",
  "prod-wafa-1": "instant-hijab-model",
  "prod-wafa-2": "hijab-fabric-texture",
  "prod-elif-1": "hijab-fabric-texture",
  "prod-elif-2": "instant-hijab-model",
  "prod-meryem-1": "instant-hijab-model",
  "prod-meryem-2": "hijab-fabric-texture",
  "prod-aaliyah-1": "hijab-fabric-texture",
  "prod-aaliyah-2": "instant-hijab-model",
  "prod-rayyan-1": "sports-hijab-fabric",
  "prod-rayyan-2": "sports-hijab-model",
  "prod-sakina-1": "sports-hijab-model",
  "prod-sakina-2": "sports-hijab-fabric",
  "prod-yumna-1": "sports-hijab-fabric",
  "prod-yumna-2": "sports-hijab-model",
  "prod-batul-1": "sports-hijab-model",
  "prod-batul-2": "sports-hijab-fabric",
  "prod-iklas-1": "sports-hijab-fabric",
  "prod-iklas-2": "sports-hijab-model",
  "prod-zara-1": "sports-hijab-model",
  "prod-zara-2": "sports-hijab-fabric",
  "prod-johara-1": "luxury-hijab-silk",
  "prod-johara-2": "luxury-hijab-detail",
  "prod-almas-1": "luxury-hijab-detail",
  "prod-almas-2": "luxury-hijab-silk",
  "prod-yakoot-1": "luxury-hijab-silk",
  "prod-yakoot-2": "luxury-hijab-detail",
  "prod-zumurrud-1": "luxury-hijab-detail",
  "prod-zumurrud-2": "luxury-hijab-silk",
  "prod-lulu-1": "luxury-hijab-silk",
  "prod-lulu-2": "luxury-hijab-detail",
  "prod-marjan-1": "luxury-hijab-detail",
  "prod-marjan-2": "luxury-hijab-silk",
  "prod-suhaila-1": "jilbab-flatlay",
  "prod-suhaila-2": "jilbab-model",
  "prod-widyan-1": "jilbab-model",
  "prod-widyan-2": "abaya-seam-detail",
  "prod-thuraya-1": "abaya-seam-detail",
  "prod-thuraya-2": "jilbab-flatlay",
  "prod-qamar-1": "jilbab-flatlay",
  "prod-qamar-2": "jilbab-model",
  "prod-najma-1": "jilbab-model",
  "prod-najma-2": "abaya-seam-detail",
  "prod-roshan-1": "abaya-seam-detail",
  "prod-roshan-2": "jilbab-flatlay",
  "prod-husna-1": "innercap-rows",
  "prod-husna-2": "innercap-model",
  "prod-afra-1": "innercap-model",
  "prod-afra-2": "innercap-rows",
  "prod-bushra-1": "innercap-rows",
  "prod-bushra-2": "innercap-model",
  "prod-dalia-1": "innercap-model",
  "prod-dalia-2": "innercap-rows",
  "prod-insiya-1": "innercap-rows",
  "prod-insiya-2": "innercap-model",
  "prod-kawthar-1": "innercap-model",
  "prod-kawthar-2": "innercap-rows",
  "prod-sabiha-1": "niqab-fabric",
  "prod-sabiha-2": "hijab-flatlay-chiffon",
  "prod-ghina-1": "hijab-flatlay-chiffon",
  "prod-ghina-2": "niqab-fabric",
  "prod-rand-1": "niqab-fabric",
  "prod-rand-2": "hijab-flatlay-chiffon",
  "prod-lamis-1": "hijab-flatlay-chiffon",
  "prod-lamis-2": "niqab-fabric",
  "prod-nisreen-1": "niqab-fabric",
  "prod-nisreen-2": "hijab-flatlay-chiffon",
  "prod-yusra-1": "hijab-flatlay-chiffon",
  "prod-yusra-2": "niqab-fabric",
  "prod-samar-1": "scarves-stack",
  "prod-samar-2": "scarf-model",
  "prod-lina-1": "scarf-model",
  "prod-lina-2": "scarves-stack",
  "prod-nawal-1": "scarves-stack",
  "prod-nawal-2": "scarf-model",
  "prod-rasha-1": "scarf-model",
  "prod-rasha-2": "scarves-stack",
  "prod-dima-1": "scarves-stack",
  "prod-dima-2": "scarf-model",
  "prod-celine-1": "scarf-model",
  "prod-celine-2": "scarves-stack",

  // Fabrics
  "fabric-nida": "fabric-nida-matte",
  "fabric-korean-nida": "fabric-korean-nida-sheen",
  "fabric-zoom": "fabric-zoom-weave",
  "fabric-chiffon": "fabric-chiffon-sheer",
  "fabric-cotton": "fabric-cotton-texture",
  "fabric-jersey": "fabric-jersey-stretch",
  "fabric-silk": "fabric-silk-sheen",
  "fabric-linen": "fabric-linen-texture",
  "fabric-crepe": "fabric-crepe-texture",
  "fabric-georgette": "fabric-georgette-crinkle",
  "fabric-rayon": "fabric-rayon-drape",
  "fabric-viscose": "fabric-viscose-weave",
  "fabric-blends": "fabric-premium-blends-stack",

  // Categories — hero + card share a photo (never rendered together)
  "cat-hijabs-hero": "hijab-flatlay-chiffon",
  "cat-hijabs-card": "hijab-fashion-model",
  "cat-abayas-hero": "abaya-mannequin",
  "cat-abayas-card": "abaya-model",
  "cat-niqabs-hero": "niqab-fabric",
  "cat-niqabs-card": "niqab-fabric",
  "cat-prayer-hero": "prayer-dress-flatlay",
  "cat-prayer-card": "prayer-dress-model",
  "cat-khimars-hero": "khimar-mannequin",
  "cat-khimars-card": "khimar-model",
  "cat-jilbabs-hero": "jilbab-flatlay",
  "cat-jilbabs-card": "jilbab-model",
  "cat-innercaps-hero": "innercap-rows",
  "cat-innercaps-card": "innercap-model",
  "cat-scarves-hero": "scarves-stack",
  "cat-scarves-card": "scarf-model",
  "cat-instant-hero": "hijab-flatlay-chiffon",
  "cat-instant-card": "instant-hijab-model",
  "cat-sports-hero": "sports-hijab-fabric",
  "cat-sports-card": "sports-hijab-model",
  "cat-luxury-hero": "luxury-hijab-silk",
  "cat-luxury-card": "luxury-hijab-detail",

  // Home sections
  "home-hero": "abaya-model",
  "home-manufacturing": "factory-floor-wide",
  "home-private-label": "design-desk",
  "instagram-0": "abaya-model",
  "instagram-1": "hijab-fashion-model",
  "instagram-2": "scarf-model",
  "instagram-3": "luxury-hijab-silk",
  "instagram-4": "kaftan-model",
  "instagram-5": "sports-hijab-model",

  // Page heroes
  "products-hero": "hijab-color-range",
  "faq-hero": "certification-documents",
  "fabrics-hero": "fabric-roll-generic",
  "oem-hero": "design-desk",
  "export-hero": "shipping-containers",
  "contact-hero": "design-desk",
  "mfg-hero": "factory-floor-wide",
  "cert-hero": "certification-documents",
  "gallery-hero": "factory-floor-wide",
  "blog-hero": "factory-floor-wide",

  // Manufacturing process stages
  "mfg-inspection": "fabric-roll-generic",
  "mfg-cutting": "cutting-table",
  "mfg-stitching": "sewing-floor",
  "mfg-embroidery": "embroidery-closeup",
  "mfg-finishing": "abaya-seam-detail",
  "mfg-qc": "qc-inspection",
  "mfg-packaging": "warehouse-cartons",
  "mfg-warehouse": "shipping-containers",

  // Blog covers
  "blog-1-cover": "fabric-roll-generic",
  "blog-2-cover": "fabric-swatch-cards",
  "blog-3-cover": "design-desk",
  "blog-4-cover": "shipping-containers",
  "blog-5-cover": "khimar-mannequin",
  "blog-6-cover": "khimar-model",
  "blog-7-cover": "jilbab-flatlay",

  // About page
  "about-hero": "factory-exterior",
  "about-story": "design-desk",
  "about-philosophy": "qc-inspection",
  "leader-Imran Sheikh": "business-headshot-1",
  "leader-Sana Ansari": "business-headshot-2",
  "leader-Zaid Khan": "business-headshot-3",
  "leader-Ayesha Merchant": "business-headshot-4",

  // Gallery grid
  "gallery-factory-1": "factory-exterior",
  "gallery-cutting-1": "cutting-table",
  "gallery-stitching-1": "sewing-floor",
  "gallery-embroidery-1": "embroidery-closeup",
  "gallery-product-1": "hijab-flatlay-chiffon",
  "gallery-product-2": "kaftan-model",
  "gallery-packaging-1": "warehouse-cartons",
  "gallery-warehouse-1": "warehouse-cartons",
  "gallery-shipping-1": "shipping-containers",
  "gallery-exhibition-1": "trade-exhibition-booth",
  "gallery-fabric-1": "fabric-swatch-cards",
  "gallery-team-1": "qc-inspection",
};

/**
 * Resolves a content seed to a real, verified stock photo where mapped,
 * falling back to a deterministic Lorem Picsum placeholder for anything new
 * that hasn't been curated yet — so a missing mapping degrades gracefully
 * instead of breaking the page.
 */
export function placeholder(seed: string, alt: string, width = 1200, height = 900): ImageAsset {
  const theme = SEED_THEME_MAP[seed];
  const src = theme
    ? THEME_PHOTOS[theme]
    : `https://picsum.photos/seed/${encodeURIComponent(seed)}/${width}/${height}`;
  return { src, alt, width, height };
}
