import type { Country } from "./types";

export const countries: Country[] = [
  { name: "United Arab Emirates", region: "Middle East", code: "AE" },
  { name: "Saudi Arabia", region: "Middle East", code: "SA" },
  { name: "Qatar", region: "Middle East", code: "QA" },
  { name: "Kuwait", region: "Middle East", code: "KW" },
  { name: "Bahrain", region: "Middle East", code: "BH" },
  { name: "Oman", region: "Middle East", code: "OM" },
  { name: "Jordan", region: "Middle East", code: "JO" },
  { name: "Turkey", region: "Middle East", code: "TR" },
  { name: "Iraq", region: "Middle East", code: "IQ" },
  { name: "Lebanon", region: "Middle East", code: "LB" },
  { name: "United Kingdom", region: "Europe", code: "GB" },
  { name: "Germany", region: "Europe", code: "DE" },
  { name: "France", region: "Europe", code: "FR" },
  { name: "Netherlands", region: "Europe", code: "NL" },
  { name: "Belgium", region: "Europe", code: "BE" },
  { name: "Sweden", region: "Europe", code: "SE" },
  { name: "Italy", region: "Europe", code: "IT" },
  { name: "Spain", region: "Europe", code: "ES" },
  { name: "Ireland", region: "Europe", code: "IE" },
  { name: "Norway", region: "Europe", code: "NO" },
  { name: "United States", region: "North America", code: "US" },
  { name: "Canada", region: "North America", code: "CA" },
  { name: "Mexico", region: "North America", code: "MX" },
  { name: "Australia", region: "Oceania", code: "AU" },
  { name: "New Zealand", region: "Oceania", code: "NZ" },
  { name: "South Africa", region: "Africa", code: "ZA" },
  { name: "Nigeria", region: "Africa", code: "NG" },
  { name: "Egypt", region: "Africa", code: "EG" },
  { name: "Morocco", region: "Africa", code: "MA" },
  { name: "Kenya", region: "Africa", code: "KE" },
  { name: "Tanzania", region: "Africa", code: "TZ" },
  { name: "Algeria", region: "Africa", code: "DZ" },
  { name: "Tunisia", region: "Africa", code: "TN" },
  { name: "Malaysia", region: "Asia", code: "MY" },
  { name: "Indonesia", region: "Asia", code: "ID" },
  { name: "Singapore", region: "Asia", code: "SG" },
  { name: "Pakistan", region: "Asia", code: "PK" },
  { name: "Bangladesh", region: "Asia", code: "BD" },
  { name: "India", region: "Asia", code: "IN" },
  { name: "Sri Lanka", region: "Asia", code: "LK" },
  { name: "Brunei", region: "Asia", code: "BN" },
  { name: "Maldives", region: "Asia", code: "MV" },
];

export const regions = Array.from(new Set(countries.map((c) => c.region)));
